services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: bash -lc "mix phx.server"
    environment:
      MIX_ENV: dev
      PHX_PORT: "4000"
      PHX_HOST: "0.0.0.0"
      STATSD_HOST: datadog-agent
      STATSD_PORT: "8125"
      DD_ENV: local
      DD_SERVICE: metrics_demo
      DD_VERSION: 0.1.0
    ports:
      - "4000:4000"
    depends_on:
      - datadog-agent
    # If you hit an ARM manifest issue on Apple Silicon, uncomment:
    # platform: "linux/amd64"

  datadog-agent:
    image: datadog/agent:7
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE:-datadoghq.eu}
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_ENV: ${DD_ENV:-local}
      DD_SERVICE: metrics_demo
      DD_VERSION: 0.1.0
    ports:
      - "8125:8125/udp"
