# lib/metrics_demo/application.ex
defmodule MetricsDemo.Application do
  @moduledoc false
  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Telemetry supervisor (generated by Phoenix)
      MetricsDemoWeb.Telemetry,
      # PubSub for Phoenix
      {Phoenix.PubSub, name: MetricsDemo.PubSub},
      # Start the Endpoint (http/https)
      MetricsDemoWeb.Endpoint
    ]

    # Open the DogStatsD UDP socket (Statix) so we can emit custom metrics
    :ok = MetricsDemo.Statsd.connect()

    opts = [strategy: :one_for_one, name: MetricsDemo.Supervisor]
    Supervisor.start_link(children, opts)
  end

  @impl true
  def config_change(changed, _new, removed) do
    MetricsDemoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end
